name: Ubuntu-Grdp
on: 
  workflow_dispatch:
   inputs:
     Auth:
        description: 'GRDP Authorizationcode'
        required: true
        default: 'null'
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps: 
    
    - name: generate script
      run: |
           touch setup.sh
           echo "${{ github.event.inputs.logLevel }}" >> "setup.sh"
